exe := "app"

alias b := build
alias r := run
alias br := buildrun

configure:
	cmake -S . -B ./build -D CMAKE_BUILD_TYPE=Debug
build:
	cmake --build ./build/.
release:
	cmake -S . -B ./release -D CMAKE_BUILD_TYPE=Debug
	cmake --build ./release/.
run:
	./build/{{exe}}

buildrun: build run